### ISSUE TITLE
cargo-strip

### ISSUE THREAD

**Issue by guedou** [johnthagen/min-sized-rust#11]
Thanks a lot for this repository. It contains a lot of useful information. I found that stripping cargo generated binaries is a bit painful as you need to identify their names manually.

To simplify the process, I released cargo-strip over the week-end that automates this. It could be improved but works fine for my needs.

**Comment by johnthagen** [comment]
@guedou Nice package! Given that it's new, I'll probably just add a small note for people to consider checking it out.

I also thought I'd recognized your username -- turns out you maintain `scapy`, another great package!

**Comment by johnthagen** [comment]
Fixed in fcdab27363952998ba9fb333d72e6cc8a4a1b48d

**Comment by guedou** [comment]
Thanks a lot for the update. I hope that this project will help other people.
