### ISSUE TITLE
Xargo: Suggest overriding the toolchain to nightly instead of changing it for the whole system

### ISSUE THREAD

**Issue by eddyp** [johnthagen/min-sized-rust#13]
In production environments and many other places it is desirable not to depend on non-stable features, as much as possible. As a consequence, I suggest to replace the line that changes the toolchain to nightly globally, to an override, to change only for the current project:

```
 rustup default nightly
```

to be replaced with:
```
rustup override set nightly 
```

**Comment by danielhenrymantilla** [comment]
Or even better (for those folders which are also a repository): create a `rust-toolchain` file with `nightly` in it, like `clippy` does for its own repo:

https://github.com/rust-lang/rust-clippy/blob/master/rust-toolchain#L1

**Comment by johnthagen** [comment]
@eddyp Thanks for the suggestion, implemented in 45bdfd20b5a34fe956b6a7812edd2c744fee4cd5
