### ISSUE TITLE
1.45.0 is now stable :)

### ISSUE THREAD

**Issue by h5rdly** [johnthagen/min-sized-rust#18]
Thanks for this great repo!

Just wanted to point out that in the `strip Symbols from Binary` section, it mentions `nightly 1.45.0`, however, this is now a stable version.

**Comment by lzutao** [comment]
It is still a nightly option in rustc.

**Comment by h5rdly** [comment]
I just did `rustup update stable` and got me `1.45.1` :)

**Comment by lzutao** [comment]
Yeah. Stable rustc cannot be passed -Z flag like `-Z strip=symbols`. Only nightly rustc can be.

**Comment by h5rdly** [comment]
You're right, just tried and it asks for nightly Cargo. Is this a glitch, i.e. they forgot to move it to the "regular" flags section?

**Comment by lzutao** [comment]
They didn't forget that. Either they don't think `strip` flag is ready for stabilization or nobody proposes it.

**Comment by corbinu** [comment]
@h5rdly The tracking issue is here https://github.com/rust-lang/rust/issues/72110 you can watch for that to get tagged "disposition-merge". It will then be in the next stable Rust that is released. Until then it will be in each nightly starting with back when 1.45 was nightly. Hope this helps.
