### ISSUE TITLE
Mention sstrip

### ISSUE THREAD

**Issue by ssokolow** [johnthagen/min-sized-rust#21]
For the sake of completeness, it'd probably be a good idea to mention the `sstrip` utility from [ELFkickers](http://www.muppetlabs.com/~breadbox/software/elfkickers.html).

As [this mirror](https://github.com/aunali1/super-strip) explains:

> Most ELF executables are built with both a program header table and a section header table. However, only the former is required in order for the OS to load, link and execute a program. sstrip attempts to extract the ELF header, the program header table, and its contents, leaving everything else in the bit bucket. It can only remove parts of the file that occur at the end, after the parts to be saved. However, this almost always includes the section header table, along with a few other sections that are not involved in program loading and execution.
>
> It should be noted that most programs that work with ELF files are dependent on the section header table as an index to the file's contents. Thus, utilities such as gdb and objdump will often have limited functionality when working with an executable with no section header table. Some other utilities may refuse to work with them at all.

Basically, it's a tool primarily used for things like saving flash memory on embedded Linux devices which will shave a few more bytes off what the regular `strip` utility produces.

**Comment by johnthagen** [comment]
Thanks for the contribution.

Do you think it's sufficient to just add a little "See Also: " entry in the `strip` section so curious users can check it out? Is the GitHub page the best one to link to? https://github.com/BR903/ELFkickers

**Comment by ssokolow** [comment]
Yeah, I think a "See Also:" would work as long as you make it clear which of the ELFKickers tools you're pointing people at.

If you do link to the GitHub page, make sure you clarify that it should be run after `strip` since the GitHub page's description isn't as clear about that as the website's description.

**Comment by johnthagen** [comment]
Closed in 3fa7a9f0ee89e4a06fad0417e172e103b1465f83
