### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by vazhnov** [johnthagen/min-sized-rust#22]
Hello!

Could you please add information about license of this repository — is it allowed to copy, change and use the code examples and documentation in any purpose?
It would be great to see any popular open source license.

**Comment by johnthagen** [comment]
Good catch, I'm surprised this has been missed.

Closed in 2253a75d5051a0c5c31485fe6c3337d07898ff30

**Comment by vazhnov** [comment]
MIT — great!
Thank you very much!
