### ISSUE TITLE
How to min size on windows? 

### ISSUE THREAD

**Issue by akaylh** [johnthagen/min-sized-rust#25]

**Comment by johnthagen** [comment]
Hello, most of these techniques will work on Windows. Those that don't (for example `strip`: https://github.com/johnthagen/min-sized-rust#strip-symbols-from-binary) are annotated with a `OS | *nix` badge.

The CI currently builds for Windows to verify this:

https://github.com/johnthagen/min-sized-rust/blob/2253a75d5051a0c5c31485fe6c3337d07898ff30/.travis.yml#L11

**Comment by analytik** [comment]
The associated Travis project doesn't seem to exist, and neither of the min-sized folders build on Windows currently. Is there anyone who made them work on Windows?

**Comment by johnthagen** [comment]
Some of our CI runs on Windows

https://github.com/johnthagen/min-sized-rust/blob/66a1fd90eead93d9e0472a3a1a88e185ae8c1761/.github/workflows/build.yml#L10

**Comment by analytik** [comment]
Ah, my apologies, somehow I overlooked the github actions. 

Still, is it possible / feasible to get `no_std` and `no_main` versions running on Windows?

**Comment by johnthagen** [comment]
If I recall, the hold up was the `libc` dependency we were using:

https://github.com/johnthagen/min-sized-rust/blob/66a1fd90eead93d9e0472a3a1a88e185ae8c1761/no_std/Cargo.toml#L9

But I don't think there is a technical reason that these can't be built on Windows.

**Comment by johnthagen** [comment]
@analytik Please see

- #62 
- #63

**Comment by analytik** [comment]
Thank you so much! They both work as intended. (3kB for debug and 2.5kB for release for the no_std.)

I'm too new to Rust to have figured it out by myself, and this repo has been linked all over the internet as the de-facto standard example for min-sizing, so I really appreciate the inclusion.

**Comment by zinkkkk** [comment]
On windows if i use the stub from https://github.com/mcountryman/min-sized-rust-windows and this inside a build.rs i can get my hello world down to 656 bytes

`fn main() {
    println!("cargo:rustc-link-arg-bins=/ALIGN:8");
    println!("cargo:rustc-link-arg-bins=/MERGE:.rdata=.text");
    println!("cargo:rustc-link-arg-bins=/MERGE:.pdata=.text");
    println!("cargo:rustc-link-arg-bins=/EMITPOGOPHASEINFO");
    println!("cargo:rustc-link-arg-bins=/STUB:stub.exe");
}`
