### ISSUE TITLE
Mention stripping additional sections to slightly reduce binary size

### ISSUE THREAD

**Issue by cottnn** [johnthagen/min-sized-rust#39]
It seems that there are some sections in the binary produced by `rustc` that can be stripped without (?) impacting the program behavior. I did some testing on the `x86_64-unknown-linux-musl` target with `#![no_main]`, and I successfully stripped the following sections on the "Hello world" binary:
```
.comment
.init_array
.dynsym
.gnu.hash
.fini_array
.eh_frame
.eh_frame_hdr
.dynstr
.plt
.plt.got
.tdata
.got
.tbss
```
Some of these sections are probably necessary for some binaries, or they may subtly corrupt the program when stripped, so further research should be done. At the very least, I think that the `.comment` and `.gnu.hash` sections can be freely stripped, although this will only shave off a couple bytes. Stripping `.gnu.hash` leads to UPX refusing to pack the executable, though.

**Comment by johnthagen** [comment]
Thanks for the feedback.

I'm hesitant to add any general guidelines that we aren't sure would apply to all cases. For example, if these sections are truly never needed, it's surprising `strip` wouldn't remove them.

I think the best way to share this content would be some kind of blog post about showing what gains can be had, and any other caveats that might exist.

**Comment by cottnn** [comment]
I see, thanks for the clarification. Closing
