### ISSUE TITLE
Add a reference to "A very small Rust binary indeed"

### ISSUE THREAD

**Issue by cottnn** [johnthagen/min-sized-rust#46]
https://darkcoding.net/software/a-very-small-rust-binary-indeed/

This blog post explains the same techniques used in this repo to shrink the binary size, but goes one step further to remove dependency on `libc` and use syscalls directly. I found it really useful when creating a `no_std` binary without libc.

The blog post also points out some other ideas, which can be applied to any Rust project:
- Disabling PIE (can be done with `relocation-model=static`)
- Telling the linker not to align sections (`-n` and `-N` flags)
- Removing BuildID from ELF files with `--build-id=none`

The gains from this probably only matter for really small binaries (below 10kb), so I think it's reasonable to just add a reference to the blog post in the footer.

**Comment by johnthagen** [comment]
Thanks for the suggestion!

Fixed in f6f4002220cd59a4535d60decf458276070c1dde
