### ISSUE TITLE
Shall there be another section after panic_immediate_abort, but before no_std?

### ISSUE THREAD

**Issue by vi** [johnthagen/min-sized-rust#5]
In addition to `panic_immediate_abort` it should use `!#[no_main]` and avoid `println!`.

This allows actually excluding formatting code while also using some of libstd's features.

**Comment by johnthagen** [comment]
@vi That totally sounds in scope for this repo as I think it's an important distinction. At the very least, it should be added to the README.

So would we have to print `Hello World` like:

```rust
    // Since we are passing a C string the final null character is mandatory.
    const HELLO: &'static str = "Hello, world!\n\0";
    unsafe {
        libc::printf(HELLO.as_ptr() as *const _);
    }
```

Or is there a way to print to stdout from within `libstd` or `libcore`? Ideally, if we didn't have to do C FFI in this next layer of example, that would be ideal (and portable to Windows).

**Comment by vi** [comment]
Shall I try to prepare a Hello World example with libstd, without `println!`, without `libc`?

**Comment by johnthagen** [comment]
Sure! Please make it as another subproject similar to the existing project layout.

**Comment by danielhenrymantilla** [comment]
Regarding FFI and C string literals, would you be interested in my making [`::byte-strings`](https://crates.io/crates/byte-strings) and its `c_str!` macro support `no_std`?
It currently does not since it generates a `&'static CStr`, but it wouldn't be too hard to make it return a `*const ::libc::c_char`

**Comment by johnthagen** [comment]
@danielhenrymantilla That's interesting -- nice crate. I'm not sure if this repository necessarily needs to be the location for where the latest and greatest FFI crates are. `byte-strings` looks pretty cool, but probably out of scope for usage of this repository.
