### ISSUE TITLE
Is there no way to use --gc-sections in rust?

### ISSUE THREAD

**Issue by jberryman** [johnthagen/min-sized-rust#60]
That linker option along with ffunction-sections makes a massive difference at least with haskell (where I think the flag is `split-sections`). Or further lld's identical code folding. I was hoping to learn about these here

**Comment by bjorn3** [comment]
Rustc already uses these options by default.

**Comment by jberryman** [comment]
Hm what would be the easiest way for me to verify that I wonder

**Comment by bjorn3** [comment]
You can pass `--print link-args` to rustc to verify that `--gc-sections` is passed and you can define a `#[no_mangle]` function but not call it to verify that unused functions are omitted. (without the `#[no_mangle]` rustc likely wouldn't even codegen it)

**Comment by johnthagen** [comment]
Thanks for sharing this the information, @bjorn3
