### ISSUE TITLE
UPX compresses the binary but increases the RAM usage

### ISSUE THREAD

**Issue by janflyborg** [johnthagen/min-sized-rust#76]
The UPX section should be updated to note that, while UPX reduces the binary's disk size, it increases memory usage. This is because UPX disables demand paging by fully loading the decompressed binary into memory. In RAM-constrained environments, this can have a significant impact and may worsen the situation when using UPX. 

That said, UPX might be a suitable solution for certain environments, but it comes with a trade-off. If the primary issue is the binary's size, using a compressed file system might be a more effective approach.

**Comment by NobodyXu** [comment]
I think UPX also have caching problem?

If you have more than one processes running the same binary, they might end up duplicating the decompressed binary.

Not sure when that will happen as I believe upx does have some ways to cache it, but I think whenever Linux namespace is used, or a different uid, it cannot reuse the decompressed binary.

And the binary could also be under attack as it is stored on tmpfs, initially writable.

IMHO transparent compression support from filesystem seems better, with no duplication, no way to tamper with, and decompress by block on demand.

**Comment by johnthagen** [comment]
@janflyborg Do you have a reference that mentions this increased memory usage, such as a link into the UPX docs? I'm not sure how in the weeds we want `min-sized-rust` to be here, but since we already mention the anti-virus concerns perhaps this could be okay to mention as well.

**Comment by johnthagen** [comment]
I'm going to close this as out of scope for min-sized-rust. Thanks for sharing though!
